### ISSUE TITLE
site: colour issues on main landing page

### ISSUE THREAD

**Issue by myitcv** [play-with-go/play-with-go#226]
I've tweaked the wording on the `guides.html` page and that has highlighted a couple of style issues:

<img width="1167" alt="Screen Shot 2020-11-11 at 11 58 43" src="https://user-images.githubusercontent.com/3374574/98809374-5a21a680-2415-11eb-98af-68aadd18359a.png">

This is as of https://github.com/play-with-go/play-with-go/commit/b81b7c7ebd28cbdc89a5eb3e532922f663282b40

Specifically:

* the red `<code>` blocks are not particularly clear
* the link text is almost invisible against the background

**Comment by marcosnils** [comment]
Fixed by a4d42cecb2986d13b7e01621bd0b4cabb2e04a54

**Comment by myitcv** [comment]
There's still an issue if I use a link in that text (which we definitely want to do... because people should be able to click through to the Tour of Go)

**Comment by marcosnils** [comment]
![image](https://user-images.githubusercontent.com/1578458/99025137-e4b5f300-2546-11eb-84f4-6b34912b519d.png)

That's how it looks now.
